package jobicade.betterhud.element.settings;

public interface ISetting {
    // For traversing the settings tree
    String getName();
    Iterable<? extends ISetting> getChildren();

    boolean hasValue();
    String getStringValue();
    String getDefaultValue();

	/**
	 * If {@code stringValue} is valid, sets the value accordingly.
     *
	 * @param stringValue A string as generated by {@link #getStringValue()}.
     * @return {@code true} if the value was updated.
	 */
    void loadStringValue(String stringValue);
    void loadDefaultValue();
}
