package jobicade.betterhud.element.settings;

/**
 * Implemented by settings which have a value. The method
 * {@link Setting#getStringSetting()} lets these settings describe themselves.
 */
public interface IStringSetting {
    public abstract String getStringValue();
    public abstract String getDefaultValue();

	/**
	 * If {@code stringValue} is valid, sets the value accordingly.
     *
	 * @param stringValue A string as generated by {@link #getStringValue()}.
     * @return {@code true} if the value was updated.
	 */
    public abstract void loadStringValue(String stringValue);
    public abstract void loadDefaultValue();
}
