package jobicade.betterhud.element.settings.serializer;

import jobicade.betterhud.element.settings.SettingValueException;

public abstract class SettingSerializer {
    public abstract String serialize();

    /**
     * If {@code stringValue} is valid, sets the value accordingly.
     *
     * @param stringValue A string as generated by {@link #getStringValue()}.
     * @throws SettingValueException if the setting value is invalid.
     */
    public abstract void deserialize(String serialized) throws SettingValueException;
}
