package tk.nukeduck.hud.util;

/** generic interface for objects which can be saved and restored from a
 * string representation, for use in config files */
public interface ISaveLoad {
	/** @return A {@link #setPreset(T)}-compatible
	 * representation of this object */
	String save();

	/** @param save A representation of the object to load,
	 * generated by {@link #save()} */
	void load(String save);
}
